global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 5s

  labels:
    monitor: 'kamon-prometheus-demo'

rule_files:
  - 'grafana.rules'

scrape_configs:
  - job_name: prometheus
    target_groups:
      - targets: ['localhost:9090']
  - job_name: demo
    metrics_path: /metrics
    target_groups:
      - targets: ['localhost:9000']
